# Generated by Django 6.1 on 2026-08-31 06:19

import core.storage
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmedia",
            name="file",
            field=models.FileField(
                storage=core.storage.PostsStorage(),
                upload_to=posts.models.post_media_upload_to,
            ),
        ),
    ]
