# Generated by Django 6.1 on 2026-08-29 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("device_guid", models.CharField(db_index=True, max_length=128)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web"),
                        ],
                        default="web",
                        max_length=10,
                    ),
                ),
                ("os_version", models.CharField(blank=True, max_length=50)),
                ("app_version", models.CharField(blank=True, max_length=20)),
                ("device_model", models.CharField(blank=True, max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("device_guid", "platform")},
            },
        ),
    ]
