# Generated by Django 6.1 on 2026-08-31 06:19

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=core.storage.UsersStorage(),
                upload_to="avatars/",
            ),
        ),
    ]
